
DROP TABLE IF EXISTS noisebot_input;
CREATE TABLE IF NOT EXISTS noisebot_input (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source VARBINARY(300) NOT NULL UNIQUE,
    route VARBINARY(300) NOT NULL DEFAULT '',
    previous_crawl TIMESTAMP DEFAULT '1970-01-01 00:00:01'
);

DROP TABLE IF EXISTS noisebot_output;
CREATE TABLE IF NOT EXISTS noisebot_output (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    link VARBINARY(500) NOT NULL UNIQUE,
    route VARBINARY(300) NOT NULL DEFAULT '',
    en_route SMALLINT(1) NOT NULL DEFAULT 0,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
