SET SESSION storage_engine = "InnoDB";
SET SESSION time_zone = "+0:00";
ALTER DATABASE CHARACTER SET "utf8";

DROP TABLE IF EXISTS requests;
CREATE TABLE IF NOT EXISTS requests (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARBINARY(30) NOT NULL DEFAULT '',
    request VARBINARY(3000) NOT NULL DEFAULT '',
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS document_headers;
CREATE TABLE IF NOT EXISTS document_headers (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dataset VARBINARY(100) NOT NULL UNIQUE,
    source VARBINARY(300) NOT NULL DEFAULT '',
    sourcename VARBINARY(100) NOT NULL DEFAULT '',
    col0 VARBINARY(300) NOT NULL DEFAULT '',
    col1 VARBINARY(300) NOT NULL DEFAULT '',
    col2 VARBINARY(300) NOT NULL DEFAULT '',
    col3 VARBINARY(300) NOT NULL DEFAULT '',
    col4 VARBINARY(300) NOT NULL DEFAULT '',
    col5 VARBINARY(300) NOT NULL DEFAULT '',
    col6 VARBINARY(300) NOT NULL DEFAULT '',
    col7 VARBINARY(300) NOT NULL DEFAULT '',
    col8 VARBINARY(300) NOT NULL DEFAULT '',
    col9 VARBINARY(300) NOT NULL DEFAULT ''
);

DROP TABLE IF EXISTS documents;
CREATE TABLE IF NOT EXISTS documents (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dataset VARBINARY(100) NOT NULL,
    col0 VARBINARY(200) NOT NULL DEFAULT '',
    col1 VARBINARY(200) NOT NULL DEFAULT '',
    col2 VARBINARY(200) NOT NULL DEFAULT '',
    col3 VARBINARY(200) NOT NULL DEFAULT '',
    col4 VARBINARY(200) NOT NULL DEFAULT '',
    col5 VARBINARY(200) NOT NULL DEFAULT '',
    col6 VARBINARY(200) NOT NULL DEFAULT '',
    col7 VARBINARY(200) NOT NULL DEFAULT '',
    col8 VARBINARY(200) NOT NULL DEFAULT '',
    col9 VARBINARY(200) NOT NULL DEFAULT '',
    KEY(dataset)
);

DROP TABLE IF EXISTS arrows;
CREATE TABLE IF NOT EXISTS arrows (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   source VARBINARY(500) NOT NULL,
   target VARBINARY(500) NOT NULL,
   ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP   
);

DROP TABLE IF EXISTS linkpool;
CREATE TABLE IF NOT EXISTS linkpool (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   object VARBINARY(500) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS mr_dataset;
CREATE TABLE IF NOT EXISTS mr_dataset (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   dataset_name VARBINARY(500) NOT NULL,
   dataset_value VARBINARY(5000) NOT NULL,
   KEY(dataset_name)
);

DROP TABLE IF EXISTS mr_workflow;
CREATE TABLE IF NOT EXISTS mr_workflow (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   workflow_route VARBINARY(500) NOT NULL,
   workflow_value VARBINARY(5000) NOT NULL,
   workflow_config VARBINARY(5000) NOT NULL,
   KEY(workflow_route)
);

