SET SESSION storage_engine = "InnoDB";
SET SESSION time_zone = "+0:00";
ALTER DATABASE CHARACTER SET "utf8";

CREATE TABLE IF NOT EXISTS requests (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    contact TEXT NOT NULL,
    request TEXT NOT NULL,
    context TEXT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY(contact(300))
);
CREATE TABLE IF NOT EXISTS request_responses (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    request_id INT NOT NULL,
    contact TEXT NOT NULL,
    comment TEXT NOT NULL,
    context TEXT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY(request_id)
);
CREATE TABLE IF NOT EXISTS language (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    language VARBINARY(30) NOT NULL,
    symbol VARBINARY(300) NOT NULL,
    requires TEXT NOT NULL,
    effects TEXT NOT NULL,
    KEY(language,symbol)
);
CREATE TABLE IF NOT EXISTS observations (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source TEXT NOT NULL,
    target TEXT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY(source(300))
);
CREATE TABLE IF NOT EXISTS alias (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source TEXT NOT NULL,
    target TEXT NOT NULL,
    KEY(source(300))
);
CREATE TABLE IF NOT EXISTS smtp_incoming (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    peer TEXT NOT NULL,
    mailfrom TEXT NOT NULL,
    rcpttos TEXT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS smtp_outgoing (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mailfrom TEXT NOT NULL,
    rcpttos TEXT NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data TEXT NOT NULL
);
