SET SESSION storage_engine = "InnoDB";
SET SESSION time_zone = "+0:00";
ALTER DATABASE CHARACTER SET "utf8";

DROP TABLE IF EXISTS document_headers;
CREATE TABLE document_headers (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dataset VARBINARY(100) NOT NULL UNIQUE,
    key0 VARBINARY(20) NOT NULL DEFAULT '',
    key1 VARBINARY(20) NOT NULL DEFAULT '',
    key2 VARBINARY(20) NOT NULL DEFAULT '',
    key3 VARBINARY(20) NOT NULL DEFAULT '',
    key4 VARBINARY(20) NOT NULL DEFAULT '',
    key5 VARBINARY(20) NOT NULL DEFAULT '',
    key6 VARBINARY(20) NOT NULL DEFAULT '',
    key7 VARBINARY(20) NOT NULL DEFAULT '',
    key8 VARBINARY(20) NOT NULL DEFAULT '',
    key9 VARBINARY(20) NOT NULL DEFAULT ''
);

DROP TABLE IF EXISTS documents;
CREATE TABLE documents (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dataset VARBINARY(100) NOT NULL,
    val0 VARBINARY(200) NOT NULL DEFAULT '',
    val1 VARBINARY(200) NOT NULL DEFAULT '',
    val2 VARBINARY(200) NOT NULL DEFAULT '',
    val3 VARBINARY(200) NOT NULL DEFAULT '',
    val4 VARBINARY(200) NOT NULL DEFAULT '',
    val5 VARBINARY(200) NOT NULL DEFAULT '',
    val6 VARBINARY(200) NOT NULL DEFAULT '',
    val7 VARBINARY(200) NOT NULL DEFAULT '',
    val8 VARBINARY(200) NOT NULL DEFAULT '',
    val9 VARBINARY(200) NOT NULL DEFAULT '',
    KEY(dataset)
);
